import type { LearningTask, Mistake, ProgressPoint, ResourceItem, VocabularyItem } from "./types";

export const initialTasks: LearningTask[] = [
  {
    id: "vocab-daily",
    title: "Activate 10 daily expressions",
    module: "Vocabulary",
    skill: "Vocabulary",
    difficulty: "B1",
    minutes: 10,
    status: "todo",
    goal: "Use each phrase in a short spoken sentence.",
    output: "10 original example sentences",
  },
  {
    id: "listen-housing",
    title: "Listen to a short daily English audio",
    module: "Listening Corner",
    skill: "Listening",
    difficulty: "B1",
    minutes: 12,
    status: "todo",
    goal: "Catch the problem, request, and appointment time before reading the transcript.",
    output: "3 detail answers",
  },
  {
    id: "speak-research",
    title: "Explain your research direction",
    module: "Speaking Room",
    skill: "Speaking",
    difficulty: "B2",
    minutes: 18,
    status: "todo",
    goal: "Speak for about 3 minutes with a clear problem, motivation, and challenge.",
    output: "Recording, transcript, polished version",
  },
  {
    id: "read-abstract",
    title: "Read and summarize a daily news digest",
    module: "Reading Digest",
    skill: "Reading",
    difficulty: "B2",
    minutes: 10,
    status: "todo",
    goal: "Find the research question, method, and claimed contribution.",
    output: "3-sentence summary",
  },
  {
    id: "write-research",
    title: "Write a research motivation paragraph",
    module: "Writing Studio",
    skill: "Writing",
    difficulty: "B2",
    minutes: 10,
    status: "todo",
    goal: "Write first without AI, then revise from focused feedback.",
    output: "120-word draft and revision",
  },
];

export const listeningPractice = {
  title: "Apartment repair appointment",
  audioLabel: "Daily listening audio",
  transcript:
    "Hi, this is Maya in apartment 4B. The kitchen sink has been leaking since last night. I put a bowl under it, but the water is still dripping every few seconds. Could someone come by this afternoon? I have class until two thirty, so any time after three would work. If today is too busy, tomorrow morning before ten is also okay. Please ask the repair person to knock loudly because the doorbell is not working either.",
  questions: [
    {
      id: "problem",
      prompt: "What is the main problem in the apartment?",
      answer: "The kitchen sink is leaking.",
    },
    {
      id: "today-time",
      prompt: "What time today is Maya available?",
      answer: "Any time after 3:00 p.m.",
    },
    {
      id: "backup-time",
      prompt: "What is the backup appointment time?",
      answer: "Tomorrow morning before 10:00.",
    },
  ],
};

export const readingDigest = {
  title: "Daily digest: clearer AI evaluations",
  source: "FluentLab daily digest",
  text:
    "A research team released a short report arguing that AI systems should be evaluated with more realistic tasks. The report says many benchmarks measure narrow skills, while real users need systems that can follow long instructions, admit uncertainty, and recover from mistakes. The team recommends testing models in longer workflows, comparing answers against expert feedback, and publishing failure cases instead of only success rates. The main message is simple: better evaluation can make AI progress easier to understand and safer to use.",
  prompts: [
    "Write a one-sentence main idea.",
    "List two evaluation problems mentioned in the digest.",
    "Write one question you would ask the research team.",
  ],
};

export const vocabulary: VocabularyItem[] = [
  {
    id: "clarify",
    phrase: "Could you clarify what you mean by...",
    meaning: "Ask someone to explain a point more clearly.",
    itemType: "Phrase",
    context: "Academic",
    example: "Could you clarify what you mean by a weaker assumption?",
    reviewDue: "Today",
  },
  {
    id: "getting-used",
    phrase: "I am still getting used to...",
    meaning: "Describe something that is becoming familiar but still difficult.",
    itemType: "Phrase",
    context: "Daily",
    example: "I am still getting used to speaking up in group meetings.",
    reviewDue: "Today",
  },
  {
    id: "key-challenge",
    phrase: "The key technical challenge is...",
    meaning: "Introduce the main hard part of a research problem.",
    itemType: "Phrase",
    context: "Speaking",
    example: "The key technical challenge is controlling the generalization gap.",
    reviewDue: "Tomorrow",
  },
  {
    id: "suggests-that",
    phrase: "This result suggests that...",
    meaning: "Explain what a result may imply.",
    itemType: "Phrase",
    context: "Writing",
    example: "This result suggests that the bound can be improved under smoothness.",
    reviewDue: "Friday",
  },
  {
    id: "to-put-it-another-way",
    phrase: "To put it another way...",
    meaning: "Restate an idea more clearly.",
    itemType: "Phrase",
    context: "Speaking",
    example: "To put it another way, the assumption controls how noisy the gradients can be.",
    reviewDue: "Today",
  },
  {
    id: "from-my-understanding",
    phrase: "From my understanding...",
    meaning: "Give your interpretation while leaving room for correction.",
    itemType: "Phrase",
    context: "Academic",
    example: "From my understanding, the theorem applies only when the loss is smooth.",
    reviewDue: "Today",
  },
  {
    id: "i-ran-into",
    phrase: "I ran into...",
    meaning: "Say that you met a problem or difficulty.",
    itemType: "Phrase",
    context: "Daily",
    example: "I ran into an issue with the package installation.",
    reviewDue: "Tomorrow",
  },
  {
    id: "what-i-found-interesting",
    phrase: "What I found interesting was...",
    meaning: "Introduce a point that caught your attention.",
    itemType: "Phrase",
    context: "Speaking",
    example: "What I found interesting was the gap between the bound and the experiment.",
    reviewDue: "Tomorrow",
  },
  {
    id: "could-we-schedule",
    phrase: "Could we schedule a time to...",
    meaning: "Politely ask to arrange a meeting or service.",
    itemType: "Phrase",
    context: "Daily",
    example: "Could we schedule a time to check the leaking sink?",
    reviewDue: "Friday",
  },
  {
    id: "i-would-like-to-follow-up",
    phrase: "I would like to follow up on...",
    meaning: "Return to a previous topic professionally.",
    itemType: "Phrase",
    context: "Writing",
    example: "I would like to follow up on the question about stability.",
    reviewDue: "Friday",
  },
  {
    id: "the-main-takeaway",
    phrase: "The main takeaway is...",
    meaning: "Summarize the most important point.",
    itemType: "Phrase",
    context: "Academic",
    example: "The main takeaway is that the regularizer changes the sample complexity.",
    reviewDue: "Saturday",
  },
  {
    id: "assumption",
    phrase: "assumption",
    meaning: "Something accepted as true before making an argument.",
    itemType: "Word",
    context: "Academic",
    example: "The proof depends on a stronger smoothness assumption.",
    reviewDue: "Today",
  },
  {
    id: "bound",
    phrase: "bound",
    meaning: "A limit that a value does not pass.",
    itemType: "Word",
    context: "Academic",
    example: "The new bound is tighter for small datasets.",
    reviewDue: "Today",
  },
  {
    id: "leak",
    phrase: "leak",
    meaning: "A small unwanted flow of water, gas, or information.",
    itemType: "Word",
    context: "Daily",
    example: "There is a leak under the kitchen sink.",
    reviewDue: "Today",
  },
  {
    id: "appointment",
    phrase: "appointment",
    meaning: "An arranged time to meet someone or receive a service.",
    itemType: "Word",
    context: "Daily",
    example: "The repair appointment is after three.",
    reviewDue: "Tomorrow",
  },
  {
    id: "uncertainty",
    phrase: "uncertainty",
    meaning: "A state of not being completely sure.",
    itemType: "Word",
    context: "Academic",
    example: "The model should admit uncertainty when the evidence is weak.",
    reviewDue: "Tomorrow",
  },
  {
    id: "workflow",
    phrase: "workflow",
    meaning: "A sequence of steps used to finish a task.",
    itemType: "Word",
    context: "Writing",
    example: "The evaluation should test the whole workflow.",
    reviewDue: "Tomorrow",
  },
  {
    id: "realistic",
    phrase: "realistic",
    meaning: "Close to real situations or practical needs.",
    itemType: "Word",
    context: "Writing",
    example: "The benchmark should include realistic user tasks.",
    reviewDue: "Friday",
  },
  {
    id: "recover",
    phrase: "recover",
    meaning: "To return to a better state after a mistake or problem.",
    itemType: "Word",
    context: "Daily",
    example: "A useful assistant should recover from a wrong first answer.",
    reviewDue: "Friday",
  },
  {
    id: "narrow",
    phrase: "narrow",
    meaning: "Limited in range or scope.",
    itemType: "Word",
    context: "Academic",
    example: "The old benchmark measures a narrow skill.",
    reviewDue: "Saturday",
  },
  {
    id: "feedback",
    phrase: "feedback",
    meaning: "Comments that help someone improve.",
    itemType: "Word",
    context: "Speaking",
    example: "Expert feedback makes the evaluation more useful.",
    reviewDue: "Saturday",
  },
];

export const mistakes: Mistake[] = [
  {
    id: "promote-research",
    skill: "Speaking",
    original: "I want to promote my research to my advisor.",
    correction: "I want to present my research to my advisor.",
    note: "Use present, explain, or discuss for research ideas. Promote sounds like marketing.",
    status: "reviewing",
  },
  {
    id: "listen-question",
    skill: "Listening",
    original: "Missed appointment time in housing dialogue.",
    correction: "Listen for time markers after repair or appointment verbs.",
    note: "Focus on phrases such as come by, available, schedule, and slot.",
    status: "new",
  },
  {
    id: "research-about",
    skill: "Writing",
    original: "My research is about how to make theory better.",
    correction: "My research studies how to develop sharper theoretical guarantees for learning algorithms.",
    note: "Replace vague academic nouns with the exact object and goal.",
    status: "improved",
  },
];

export const resources: ResourceItem[] = [
  {
    id: "mit-lecture",
    title: "MIT OCW lecture: Introduction to Machine Learning",
    source: "MIT OCW",
    type: "Lecture",
    skill: "Listening",
    url: "https://ocw.mit.edu/courses/6-036-introduction-to-machine-learning-fall-2020/resources/lecture-1-introduction/",
  },
  {
    id: "ted-ed-sleep",
    title: "TED-Ed lesson: The benefits of a good night's sleep",
    source: "TED-Ed",
    type: "Video",
    skill: "Listening",
    url: "https://ed.ted.com/lessons/the-benefits-of-a-good-night-s-sleep-shai-marcu",
  },
  {
    id: "voa-lesson-welcome",
    title: "VOA Let's Learn English: Welcome",
    source: "VOA Learning English",
    type: "Video",
    skill: "Listening",
    url: "https://learningenglish.voanews.com/a/lets-learn-english-level-1-lesson-1-welcome/3179879.html",
  },
  {
    id: "arxiv-abstracts",
    title: "arXiv CS recent abstracts",
    source: "arXiv",
    type: "Article",
    skill: "Reading",
    url: "https://arxiv.org/list/cs/recent",
  },
  {
    id: "news-in-levels",
    title: "Daily leveled news for reading summaries",
    source: "News in Levels",
    type: "Article",
    skill: "Reading",
    url: "https://www.newsinlevels.com/",
  },
  {
    id: "conversation-science",
    title: "Readable research and science articles",
    source: "The Conversation",
    type: "Article",
    skill: "Reading",
    url: "https://theconversation.com/us",
  },
  {
    id: "youglish",
    title: "Expression pronunciation examples",
    source: "YouGlish",
    type: "Tool",
    skill: "Speaking",
    url: "https://youglish.com",
  },
];

export const progress: ProgressPoint[] = [
  { label: "Mon", minutes: 46, completed: 4 },
  { label: "Tue", minutes: 62, completed: 5 },
  { label: "Wed", minutes: 35, completed: 3 },
  { label: "Thu", minutes: 58, completed: 4 },
  { label: "Fri", minutes: 0, completed: 0 },
  { label: "Sat", minutes: 0, completed: 0 },
  { label: "Sun", minutes: 0, completed: 0 },
];

export const dailySpeakingTopicSets = [
  [
    "Explain your current research problem to a new lab member who knows machine learning but not learning theory. Include the problem, why it matters, and one concrete example.",
    "Call your apartment manager about a kitchen sink leak. Explain when it started, what you already tried, and two times when you are available.",
    "Summarize a paper you read this week for a one-minute group meeting update. Include the motivation, method, and one limitation.",
    "Ask a seminar speaker about one theorem assumption. State the assumption, why it seems strong, and ask whether it can be weakened.",
  ],
  [
    "Introduce yourself to a visiting professor after a seminar. Mention your research area, one recent question you are studying, and why you enjoyed the talk.",
    "Explain why your research problem matters to a first-year PhD student. Use one simple analogy and one technical sentence.",
    "Describe a delayed package problem to customer service. Give the order context, the problem, and the action you want.",
    "Give a short weekly update to your advisor. Mention what you finished, what is blocked, and what you will try next.",
  ],
  [
    "Compare two assumptions from recent papers. Explain which one is stronger, why it matters, and what changes in the result.",
    "Describe your ideal research routine to a new classmate. Include deep work time, meetings, reading, and recovery.",
    "Ask a polite follow-up question after a confusing talk. First summarize what you understood, then ask for the missing step.",
    "Explain the intuition of one theorem without formulas. Use a concrete example and one sentence about the proof idea.",
  ],
];

export function getDailySpeakingTopics(now = new Date()) {
  const start = new Date(now.getFullYear(), 0, 0);
  const dayIndex = Math.floor((now.getTime() - start.getTime()) / 86_400_000);
  return dailySpeakingTopicSets[dayIndex % dailySpeakingTopicSets.length];
}
