from __future__ import annotations

from datetime import date

from .models import (
    AppState,
    DailyPlan,
    LearnerProfile,
    LearningTask,
    Mistake,
    ProgressPoint,
    ResourceItem,
    UserSettings,
    VocabularyItem,
)


def build_seed_state(today: date | None = None) -> AppState:
    plan_date = today or date.today()
    tasks = [
        LearningTask(
            id="vocab-daily",
            title="Activate 10 daily expressions",
            module="Vocabulary",
            skill="Vocabulary",
            difficulty="B1",
            minutes=10,
            goal="Use each phrase in a short spoken sentence.",
            output="10 original example sentences",
        ),
        LearningTask(
            id="listen-housing",
            title="Listen to a short daily English audio",
            module="Listening Corner",
            skill="Listening",
            difficulty="B1",
            minutes=12,
            goal="Catch the problem, request, and appointment time before reading the transcript.",
            output="3 detail answers",
        ),
        LearningTask(
            id="speak-research",
            title="Explain your research direction",
            module="Speaking Room",
            skill="Speaking",
            difficulty="B2",
            minutes=18,
            goal="Speak for about 3 minutes with a clear problem, motivation, and challenge.",
            output="Recording, transcript, polished version",
        ),
        LearningTask(
            id="read-abstract",
            title="Read and summarize a daily news digest",
            module="Reading Digest",
            skill="Reading",
            difficulty="B2",
            minutes=10,
            goal="Find the research question, method, and claimed contribution.",
            output="3-sentence summary",
        ),
        LearningTask(
            id="write-research",
            title="Write a research motivation paragraph",
            module="Writing Studio",
            skill="Writing",
            difficulty="B2",
            minutes=10,
            goal="Write first without AI, then revise from focused feedback.",
            output="120-word draft and revision",
        ),
    ]

    return AppState(
        profile=LearnerProfile(
            preferred_topics=[
                "AI theory",
                "machine learning",
                "optimization",
                "research life",
                "daily life abroad",
            ],
            weaknesses=[
                "listening",
                "speaking",
                "independent writing",
                "daily expressions",
            ],
        ),
        settings=UserSettings(),
        daily_plan=DailyPlan(
            id=f"daily-{plan_date.isoformat()}",
            plan_date=plan_date,
            target_minutes=60,
            total_estimated_minutes=sum(task.minutes for task in tasks),
            completion_rate=0,
            focus=["Speaking", "Listening", "Writing", "Vocabulary"],
            tasks=tasks,
        ),
        vocabulary=[
            VocabularyItem(
                id="clarify",
                phrase="Could you clarify what you mean by...",
                meaning="Ask someone to explain a point more clearly.",
                item_type="Phrase",
                context="Academic",
                example="Could you clarify what you mean by a weaker assumption?",
                review_due="Today",
            ),
            VocabularyItem(
                id="getting-used",
                phrase="I am still getting used to...",
                meaning="Describe something that is becoming familiar but still difficult.",
                item_type="Phrase",
                context="Daily",
                example="I am still getting used to speaking up in group meetings.",
                review_due="Today",
            ),
            VocabularyItem(
                id="key-challenge",
                phrase="The key technical challenge is...",
                meaning="Introduce the main hard part of a research problem.",
                item_type="Phrase",
                context="Speaking",
                example="The key technical challenge is controlling the generalization gap.",
                review_due="Tomorrow",
            ),
            VocabularyItem(
                id="suggests-that",
                phrase="This result suggests that...",
                meaning="Explain what a result may imply.",
                item_type="Phrase",
                context="Writing",
                example="This result suggests that the bound can be improved under smoothness.",
                review_due="Friday",
            ),
            VocabularyItem(
                id="to-put-it-another-way",
                phrase="To put it another way...",
                meaning="Restate an idea more clearly.",
                item_type="Phrase",
                context="Speaking",
                example="To put it another way, the assumption controls how noisy the gradients can be.",
                review_due="Today",
            ),
            VocabularyItem(
                id="from-my-understanding",
                phrase="From my understanding...",
                meaning="Give your interpretation while leaving room for correction.",
                item_type="Phrase",
                context="Academic",
                example="From my understanding, the theorem applies only when the loss is smooth.",
                review_due="Today",
            ),
            VocabularyItem(
                id="i-ran-into",
                phrase="I ran into...",
                meaning="Say that you met a problem or difficulty.",
                item_type="Phrase",
                context="Daily",
                example="I ran into an issue with the package installation.",
                review_due="Tomorrow",
            ),
            VocabularyItem(
                id="what-i-found-interesting",
                phrase="What I found interesting was...",
                meaning="Introduce a point that caught your attention.",
                item_type="Phrase",
                context="Speaking",
                example="What I found interesting was the gap between the bound and the experiment.",
                review_due="Tomorrow",
            ),
            VocabularyItem(
                id="could-we-schedule",
                phrase="Could we schedule a time to...",
                meaning="Politely ask to arrange a meeting or service.",
                item_type="Phrase",
                context="Daily",
                example="Could we schedule a time to check the leaking sink?",
                review_due="Friday",
            ),
            VocabularyItem(
                id="i-would-like-to-follow-up",
                phrase="I would like to follow up on...",
                meaning="Return to a previous topic professionally.",
                item_type="Phrase",
                context="Writing",
                example="I would like to follow up on the question about stability.",
                review_due="Friday",
            ),
            VocabularyItem(
                id="the-main-takeaway",
                phrase="The main takeaway is...",
                meaning="Summarize the most important point.",
                item_type="Phrase",
                context="Academic",
                example="The main takeaway is that the regularizer changes the sample complexity.",
                review_due="Saturday",
            ),
            VocabularyItem(
                id="assumption",
                phrase="assumption",
                meaning="Something accepted as true before making an argument.",
                item_type="Word",
                context="Academic",
                example="The proof depends on a stronger smoothness assumption.",
                review_due="Today",
            ),
            VocabularyItem(
                id="bound",
                phrase="bound",
                meaning="A limit that a value does not pass.",
                item_type="Word",
                context="Academic",
                example="The new bound is tighter for small datasets.",
                review_due="Today",
            ),
            VocabularyItem(
                id="leak",
                phrase="leak",
                meaning="A small unwanted flow of water, gas, or information.",
                item_type="Word",
                context="Daily",
                example="There is a leak under the kitchen sink.",
                review_due="Today",
            ),
            VocabularyItem(
                id="appointment",
                phrase="appointment",
                meaning="An arranged time to meet someone or receive a service.",
                item_type="Word",
                context="Daily",
                example="The repair appointment is after three.",
                review_due="Tomorrow",
            ),
            VocabularyItem(
                id="uncertainty",
                phrase="uncertainty",
                meaning="A state of not being completely sure.",
                item_type="Word",
                context="Academic",
                example="The model should admit uncertainty when the evidence is weak.",
                review_due="Tomorrow",
            ),
            VocabularyItem(
                id="workflow",
                phrase="workflow",
                meaning="A sequence of steps used to finish a task.",
                item_type="Word",
                context="Writing",
                example="The evaluation should test the whole workflow.",
                review_due="Tomorrow",
            ),
            VocabularyItem(
                id="realistic",
                phrase="realistic",
                meaning="Close to real situations or practical needs.",
                item_type="Word",
                context="Writing",
                example="The benchmark should include realistic user tasks.",
                review_due="Friday",
            ),
            VocabularyItem(
                id="recover",
                phrase="recover",
                meaning="To return to a better state after a mistake or problem.",
                item_type="Word",
                context="Daily",
                example="A useful assistant should recover from a wrong first answer.",
                review_due="Friday",
            ),
            VocabularyItem(
                id="narrow",
                phrase="narrow",
                meaning="Limited in range or scope.",
                item_type="Word",
                context="Academic",
                example="The old benchmark measures a narrow skill.",
                review_due="Saturday",
            ),
            VocabularyItem(
                id="feedback",
                phrase="feedback",
                meaning="Comments that help someone improve.",
                item_type="Word",
                context="Speaking",
                example="Expert feedback makes the evaluation more useful.",
                review_due="Saturday",
            ),
        ],
        mistakes=[
            Mistake(
                id="promote-research",
                skill="Speaking",
                original="I want to promote my research to my advisor.",
                correction="I want to present my research to my advisor.",
                note="Use present, explain, or discuss for research ideas. Promote sounds like marketing.",
                status="reviewing",
            ),
            Mistake(
                id="research-about",
                skill="Writing",
                original="My research is about how to make theory better.",
                correction="My research studies how to develop sharper theoretical guarantees for learning algorithms.",
                note="Replace vague academic nouns with the exact object and goal.",
                status="improved",
            ),
        ],
        resources=[
            ResourceItem(
                id="mit-lecture",
                title="MIT OCW lecture: Introduction to Machine Learning",
                source="MIT OCW",
                type="Lecture",
                skill="Listening",
                url="https://ocw.mit.edu/courses/6-036-introduction-to-machine-learning-fall-2020/resources/lecture-1-introduction/",
            ),
            ResourceItem(
                id="ted-ed-sleep",
                title="TED-Ed lesson: The benefits of a good night's sleep",
                source="TED-Ed",
                type="Video",
                skill="Listening",
                url="https://ed.ted.com/lessons/the-benefits-of-a-good-night-s-sleep-shai-marcu",
            ),
            ResourceItem(
                id="voa-lesson-welcome",
                title="VOA Let's Learn English: Welcome",
                source="VOA Learning English",
                type="Video",
                skill="Listening",
                url="https://learningenglish.voanews.com/a/lets-learn-english-level-1-lesson-1-welcome/3179879.html",
            ),
            ResourceItem(
                id="arxiv-abstracts",
                title="arXiv CS recent abstracts",
                source="arXiv",
                type="Article",
                skill="Reading",
                url="https://arxiv.org/list/cs/recent",
            ),
            ResourceItem(
                id="news-in-levels",
                title="Daily leveled news for reading summaries",
                source="News in Levels",
                type="Article",
                skill="Reading",
                url="https://www.newsinlevels.com/",
            ),
            ResourceItem(
                id="conversation-science",
                title="Readable research and science articles",
                source="The Conversation",
                type="Article",
                skill="Reading",
                url="https://theconversation.com/us",
            ),
        ],
        progress=[
            ProgressPoint(label="Mon", minutes=46, completed=4),
            ProgressPoint(label="Tue", minutes=62, completed=5),
            ProgressPoint(label="Wed", minutes=35, completed=3),
            ProgressPoint(label="Thu", minutes=58, completed=4),
            ProgressPoint(label="Fri", minutes=0, completed=0),
            ProgressPoint(label="Sat", minutes=0, completed=0),
            ProgressPoint(label="Sun", minutes=0, completed=0),
        ],
    )
